name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies and run e2e tests (frontend tests)
      run: |
        cd 01-Login
        yarn install
        yarn run cypress:ci
